config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index" 
  resources :birds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bird.rb
class Bird < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
    def create
        @bird = Bird.new(bird_params)
        @bird.save
        redirect_to root_path
    end

    def index
        @birds = Bird.all
    end

    def new
        @bird = Bird.new
    end
    
    private
    
    def bird_params
        params.require(:bird).permit( :saying, :author)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/views/birds/index.html.erb
<% @birds.each do |bird| %>
<p>
<%=bird.saying%>
<%=bird.author%>
</p>
<% end %>

app/views/birds/new.html.erb
<%=simple_form_for @bird do |f|=%>
<%=f.input :saying, label:"Facts"%>
<%=f.input :author%>
<%=f.button :submit%>
<% end %>

app/views/home/index.html.erb
<!-- if it is a index action, look for a folder called home, inside it will look for a file named index. 
#model view controller, place index, place.all in controller, @places . each controller sets up data for the view -->
<h1> birds </h1>
<%= link_to "more birds", new_bird_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Birds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>